modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="brainage_minigames"
version="${version}"
displayName="Brainage Minigames"
description='''Server-side custom events and Ultra Hardcore minigames.'''

[[dependencies.brainage_minigames]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="SERVER"

[[dependencies.brainage_minigames]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="SERVER"
